import Head from 'next/head'

import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Master Programming in Hindi | Learn Code With Durgesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 <div className='mt-16'>
 <Hero />
 </div>
    
    </div>
  )
}
